# EC2 Playbook
---

- name: Playbook to install packages
  hosts: all
  vars:
    ansible_user: "ubuntu"
    new_go_version: 1.19

  tasks:

  - name: Install tool packages
    become: yes
    block:

    - name: Add PHP 8.1 Repo
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Update packages
      apt:
        update_cache: yes

    - name: Install packages
      ansible.builtin.apt:
        pkg: 
          - certbot
          - build-essential
          - php8.1-fpm
          - php8.1
          - nginx
          - nginx-extras
          - unzip
          - ssl-cert
          - nmap
        state: present


  - name: Install golang
    become: yes
    become_method: sudo
    block:

    - name: Download golang tar
      get_url:
        url: "https://storage.googleapis.com/golang/go{{ new_go_version }}.linux-amd64.tar.gz"
        dest: "{{ ansible_env.HOME }}"
        mode: 0440

    - name: Extract the Go tarball
      unarchive:
        src: "{{ ansible_env.HOME }}/go{{ new_go_version }}.linux-amd64.tar.gz"
        dest: /usr/local
        copy: no
      become: yes

    - name: Create go directories in home
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0775
      with_items:
      - "{{ ansible_env.HOME }}/go"
      - "{{ ansible_env.HOME }}/go/bin"
    
    - name: Modify .bashrc
      blockinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        block: |
          export GOPATH=$HOME/go
          export GOBIN=$GOPATH/bin
          export PATH=$GOBIN:$PATH:/usr/local/go/bin  
        marker: '# {mark} ANSIBLE MANAGED BLOCK - changes for golang'
        insertafter: EOF
        create: yes